[project]
name = "pdf-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "groq==0.13.0",
    "numpy==2.1.3",
    "pypdf==5.1.0",
    "rank-bm25==0.2.2",
    "sentence-transformers==3.3.1",
    "streamlit==1.40.2",
]
